# Site settings
title: Akshay Karthik
email: akshay.karthik@gmail.com
description: "This is my portfolio and blog"
baseurl: ""
url: "http://akshaykarthik.com"
username: akshaykarthik

# Build settings
markdown: kramdown
permalink: pretty

sitepages:
	- name: about
	  url: about.html
	- name: feed
	  url: feed.xml