# Permalinks
permalink:        /blog/:year-:month-:day/:title/
relative_permalinks: true

# Setup
title:            Akshay Karthik
tagline:          Blog/Website/Portfolio
url:              http://akshaykarthik.com
paginate:         25
baseurl:          /
author:
  name:           Akshay Karthik
  url:            http://akshaykarthik.com
  email:          akshay.karthik@gmail.com

